
package sistemax.Presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sistema.LogicaNegocio.Transacciones;
import sistema.LogicaNegocio.TransaccionesProveedores;
import sistema.LogicaNegocio.TransaccionesUsuarios;
import sistemax.DAO.Usuarios;


/**
 *
 * @author BENAVIDES
 */
public final class Menu1 extends javax.swing.JFrame {

    
    Usuarios mod;
    Productos pa1= new Productos();
    UsuariosF pa2= new UsuariosF();
    Proveedor1 pa3= new Proveedor1();
    registro ru=new registro();
    
    public Menu1() {
        initComponents();
        iniciarPanel();
        
        
        this.setLocationRelativeTo(null);
        frmVentas.setVisible(false);
        
    }

    Menu1(Usuarios mod) {
        initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;
        iniciarPanel();
        
        
        
        if (mod.getIdTipo() == 1) {
            fileMenuProductos.setVisible(true);
            btnEP.setVisible(true);
            aboutMenuItem.setVisible(true);
            helpMenuUsuarios.setVisible(true);
            jMenuRegistrodeUsuarios.setVisible(true);
            jMenuIformes.setVisible(true);
            jMenuCompas.setVisible(true);
            jMenuVentas.setVisible(true);
            jMenuFacturas.setVisible(true);
        } else {
            helpMenuUsuarios.setVisible(false);
            jMenuRegistrodeUsuarios.setVisible(false);
            fileMenuProductos.setVisible(false);
            aboutMenuItem.setVisible(false);
            btnEP.setVisible(false);      
        }
    }
    
      private void iniciarPanel()
    {
        
        this.setExtendedState(Menu1.MAXIMIZED_BOTH);
        jInternalFrame1.setContentPane(pa1);
        jInternalFrame2.setContentPane(pa2);
        jInternalFrame3.setContentPane(pa3);
        
    }

    
      private void cerrar()
      {
          login lg= new login();
          String botones[] = {"Cerrar Sesion","Cancelar"};
          int eleccion = JOptionPane.showOptionDialog(this, "Seguro que decea Cerrar sesion",
                  "Cerrar Sesion",0,0, null,botones,this);
          
          if(eleccion == JOptionPane.YES_OPTION)
          {
               
               lg.setVisible(true);
               dispose(); 
          }
          else if(eleccion==JOptionPane.YES_OPTION)
          {
              System.out.println("Se cancelo el cierre");
          }
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        frmVentas = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenuProductos = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        btnEP = new javax.swing.JMenuItem();
        editMenuProveedores = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        btnProveedorEditar = new javax.swing.JMenuItem();
        helpMenuUsuarios = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuRegistrodeUsuarios = new javax.swing.JMenu();
        contentMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        jMenuIformes = new javax.swing.JMenu();
        contentMenuItem2 = new javax.swing.JMenuItem();
        RU = new javax.swing.JMenuItem();
        RP = new javax.swing.JMenuItem();
        RPRO = new javax.swing.JMenuItem();
        jMenuCompas = new javax.swing.JMenu();
        contentMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem3 = new javax.swing.JMenuItem();
        jMenuVentas = new javax.swing.JMenu();
        contentMenuItem4 = new javax.swing.JMenuItem();
        aboutMenuItem4 = new javax.swing.JMenuItem();
        jMenuFacturas = new javax.swing.JMenu();
        contentMenuItem5 = new javax.swing.JMenuItem();
        aboutMenuItem5 = new javax.swing.JMenuItem();
        btnOpciones = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();
        aboutMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusCycleRoot(false);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(300, 300));
        jInternalFrame1.setVisible(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jInternalFrame1);
        jInternalFrame1.setBounds(110, 20, 850, 550);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setVisible(false);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jInternalFrame2);
        jInternalFrame2.setBounds(520, 110, 850, 550);

        jInternalFrame3.setClosable(true);
        jInternalFrame3.setIconifiable(true);
        jInternalFrame3.setMaximizable(true);
        jInternalFrame3.setResizable(true);
        jInternalFrame3.setVisible(false);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        desktopPane.add(jInternalFrame3);
        jInternalFrame3.setBounds(150, 10, 600, 550);

        frmVentas.setVisible(true);
        frmVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmVentasMouseClicked(evt);
            }
        });

        jLabel1.setText("ID  Producto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Cantidad");

        jLabel3.setText("VENTAS");

        javax.swing.GroupLayout frmVentasLayout = new javax.swing.GroupLayout(frmVentas.getContentPane());
        frmVentas.getContentPane().setLayout(frmVentasLayout);
        frmVentasLayout.setHorizontalGroup(
            frmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmVentasLayout.createSequentialGroup()
                .addGroup(frmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmVentasLayout.createSequentialGroup()
                        .addGroup(frmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frmVentasLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frmVentasLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel3)))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        frmVentasLayout.setVerticalGroup(
            frmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmVentasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(frmVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        desktopPane.add(frmVentas);
        frmVentas.setBounds(30, 40, 590, 420);

        fileMenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shipping_products_22121 (1).png"))); // NOI18N
        fileMenuProductos.setMnemonic('f');

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("PRODUCTOS");
        fileMenuProductos.add(openMenuItem);

        btnEP.setMnemonic('s');
        btnEP.setText("Editar");
        btnEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPActionPerformed(evt);
            }
        });
        fileMenuProductos.add(btnEP);

        menuBar.add(fileMenuProductos);

        editMenuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/businessman_man_person_people_2842 (1).png"))); // NOI18N
        editMenuProveedores.setMnemonic('e');
        editMenuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuProveedoresActionPerformed(evt);
            }
        });

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("PROVEEDORES");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenuProveedores.add(cutMenuItem);

        btnProveedorEditar.setMnemonic('y');
        btnProveedorEditar.setText("Editar");
        btnProveedorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorEditarActionPerformed(evt);
            }
        });
        editMenuProveedores.add(btnProveedorEditar);

        menuBar.add(editMenuProveedores);

        helpMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin_person_user_man_2839 (2).png"))); // NOI18N
        helpMenuUsuarios.setMnemonic('h');

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("USUARIOS");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenuUsuarios.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Editar");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenuUsuarios.add(aboutMenuItem);

        menuBar.add(helpMenuUsuarios);

        jMenuRegistrodeUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/records_notes_journal_edited_9479 (2).png"))); // NOI18N
        jMenuRegistrodeUsuarios.setMnemonic('h');

        contentMenuItem1.setMnemonic('c');
        contentMenuItem1.setText("REGISTRO DE USUARIOS");
        jMenuRegistrodeUsuarios.add(contentMenuItem1);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("Registro");
        aboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRegistrodeUsuarios.add(aboutMenuItem1);

        menuBar.add(jMenuRegistrodeUsuarios);

        jMenuIformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder-documents01-1622837_121952.png"))); // NOI18N
        jMenuIformes.setMnemonic('h');

        contentMenuItem2.setMnemonic('c');
        contentMenuItem2.setText("INFORMES");
        jMenuIformes.add(contentMenuItem2);

        RU.setMnemonic('a');
        RU.setText("Reporte de Usuarios");
        RU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUActionPerformed(evt);
            }
        });
        jMenuIformes.add(RU);

        RP.setMnemonic('a');
        RP.setText("Reporte de Proveedores");
        RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPActionPerformed(evt);
            }
        });
        jMenuIformes.add(RP);

        RPRO.setMnemonic('a');
        RPRO.setText("Reporte de Productos");
        RPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPROActionPerformed(evt);
            }
        });
        jMenuIformes.add(RPRO);

        menuBar.add(jMenuIformes);

        jMenuCompas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shoppingcart_accept_compra_12832.png"))); // NOI18N
        jMenuCompas.setMnemonic('h');

        contentMenuItem3.setMnemonic('c');
        contentMenuItem3.setText("COMPRAS");
        jMenuCompas.add(contentMenuItem3);

        aboutMenuItem3.setMnemonic('a');
        aboutMenuItem3.setText("Nueva");
        aboutMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem3ActionPerformed(evt);
            }
        });
        jMenuCompas.add(aboutMenuItem3);

        menuBar.add(jMenuCompas);

        jMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice_106601.png"))); // NOI18N
        jMenuVentas.setMnemonic('h');

        contentMenuItem4.setMnemonic('c');
        contentMenuItem4.setText("VENTAS");
        contentMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItem4ActionPerformed(evt);
            }
        });
        jMenuVentas.add(contentMenuItem4);

        aboutMenuItem4.setMnemonic('a');
        aboutMenuItem4.setText("Nuevo");
        aboutMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuItem4MouseClicked(evt);
            }
        });
        aboutMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem4ActionPerformed(evt);
            }
        });
        jMenuVentas.add(aboutMenuItem4);

        menuBar.add(jMenuVentas);

        jMenuFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cashier_icon-icons.com_53629.png"))); // NOI18N
        jMenuFacturas.setMnemonic('h');

        contentMenuItem5.setMnemonic('c');
        contentMenuItem5.setText("FACTURAS");
        jMenuFacturas.add(contentMenuItem5);

        aboutMenuItem5.setMnemonic('a');
        aboutMenuItem5.setText("Nueva");
        aboutMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem5ActionPerformed(evt);
            }
        });
        jMenuFacturas.add(aboutMenuItem5);

        menuBar.add(jMenuFacturas);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1486506264-hamburger-list-menu-options-bars-stack_81469.png"))); // NOI18N
        btnOpciones.setMnemonic('h');

        btnCerrarSesion.setMnemonic('c');
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        btnOpciones.add(btnCerrarSesion);

        aboutMenuItem6.setMnemonic('a');
        aboutMenuItem6.setText("Ayuda");
        aboutMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem6ActionPerformed(evt);
            }
        });
        btnOpciones.add(aboutMenuItem6);

        menuBar.add(btnOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void RUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUActionPerformed
        TransaccionesUsuarios tr= new TransaccionesUsuarios();
        tr.mostrarReporteUsuarios();
    }//GEN-LAST:event_RUActionPerformed

    private void aboutMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem3ActionPerformed

    private void aboutMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem4ActionPerformed
        // TODO add your handling code here:
        frmVentas.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem4ActionPerformed

    private void aboutMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem5ActionPerformed

    private void btnEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPActionPerformed
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_btnEPActionPerformed

    private void aboutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem1ActionPerformed
      
       ru.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem1ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        jInternalFrame2.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void editMenuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuProveedoresActionPerformed
       
    }//GEN-LAST:event_editMenuProveedoresActionPerformed

    private void btnProveedorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorEditarActionPerformed
        jInternalFrame3.setVisible(true);
    }//GEN-LAST:event_btnProveedorEditarActionPerformed

    private void RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPActionPerformed
        TransaccionesProveedores tr= new TransaccionesProveedores();
        tr.mostrarReporteProveedores();
    }//GEN-LAST:event_RPActionPerformed

    private void RPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPROActionPerformed
        Transacciones tr= new Transacciones();
        tr.mostrarReporteProductos();
    }//GEN-LAST:event_RPROActionPerformed

    private void aboutMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem6ActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void contentMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItem4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_contentMenuItem4ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void frmVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frmVentasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_frmVentasMouseClicked

    private void aboutMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuItem4MouseClicked
        // TODO add your handling code here:
        frmVentas.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RP;
    private javax.swing.JMenuItem RPRO;
    private javax.swing.JMenuItem RU;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem3;
    private javax.swing.JMenuItem aboutMenuItem4;
    private javax.swing.JMenuItem aboutMenuItem5;
    private javax.swing.JMenuItem aboutMenuItem6;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnEP;
    private javax.swing.JMenu btnOpciones;
    private javax.swing.JMenuItem btnProveedorEditar;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem contentMenuItem1;
    private javax.swing.JMenuItem contentMenuItem2;
    private javax.swing.JMenuItem contentMenuItem3;
    private javax.swing.JMenuItem contentMenuItem4;
    private javax.swing.JMenuItem contentMenuItem5;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenuProveedores;
    private javax.swing.JMenu fileMenuProductos;
    private javax.swing.JInternalFrame frmVentas;
    private javax.swing.JMenu helpMenuUsuarios;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuCompas;
    private javax.swing.JMenu jMenuFacturas;
    private javax.swing.JMenu jMenuIformes;
    private javax.swing.JMenu jMenuRegistrodeUsuarios;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

}
